# Generated by Django 3.1.1 on 2020-09-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(default='jhh', upload_to='bg/'),
            preserve_default=False,
        ),
    ]
