# Generated by Django 3.1.1 on 2020-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0002_auto_20200930_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('news', 'News'), ('articles', 'Articles')], max_length=50),
        ),
    ]
