# Generated by Django 3.1.1 on 2020-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0003_auto_20200930_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='tag',
            field=models.ManyToManyField(to='news_blog.Tag'),
        ),
    ]
