# Generated by Django 3.1.1 on 2020-09-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('project_category', models.CharField(choices=[('', 'Choose Category'), ('contracting', 'contracting'), ('logistics', 'Logistics')], max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_cover_image', models.ImageField(upload_to='project/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio_clients.project')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
