# Generated by Django 3.1.1 on 2020-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_clients', '0002_gallery_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='hffshshs', unique=True),
            preserve_default=False,
        ),
    ]
