# Generated by Django 3.1.1 on 2020-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_clients', '0003_auto_20200930_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='project/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cover_image',
            field=models.ImageField(upload_to='project/%Y/%m/%d/'),
        ),
    ]
