# Generated by Django 3.1.1 on 2020-09-30 09:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_clients', '0005_auto_20200930_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
